### ISSUE TITLE
cannot access com.sun.jna.Pointer

### ISSUE THREAD

**Issue by SeverinAlexB** [bitcoindevkit/bdk-kotlin#69]
### Description

I got a compilation error when using `bdk-jvm 0.7.1` with the graalvm.

```
(java-compile) on project batch-payouts: Compilation failure
[ERROR] /Users/severinbuhler/git/lipa/batch-payouts/src/main/java/com/lipa/config/env/AbstractWalletEnvironment.java:[22,16] cannot access com.sun.jna.Pointer
[ERROR]   class file for com.sun.jna.Pointer not found
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
```

After some further research, turns out graalvm doesn't natively support jna.

## Solution
Add jna as a dependency to your pom.xml.
```
    <dependency>
      <groupId>com.sun.jna</groupId>
      <artifactId>jna</artifactId>
      <version>3.0.9</version>
    </dependency>
```

### How to Reproduce

Use bdk-jvm with graalvm.

### Expected Result

Should work without any additional dependencies. It's not a big issue though as the workaround is easy.

### Version

- bdk-jvm 0.7.1

### Artifact

- [X] bdk-jvm
- [ ] bdk-android

### Platform

- [ ] ARM64 Android
- [ ] 64-bit x86 Android
- [ ] 32-bit x86 Android
- [ ] 64-bit x86 Linux (kernel 2.6.32+, glibc 2.11+)
- [ ] 64-bit x86 macOS (10.7+, Lion+)
- [ ] ARM64 macOS (11.0+, Big Sur+)

**Comment by notmandatory** [comment]
Thanks for posting this for others. As long as `graalvm` doesn't include JNA I don't see any better way to do this. This could also be an issue on any other JVMs that don't also bundle the JVM lib. Since you found the solution feel free to close the issue, or you could keep it open if you want to see if anyone else has a better solution.
